# --- ClusterIP Service ---
# Exposes the application Pods on a stable IP address *within* the cluster.
# Other applications inside the cluster can reach your app via this Service's name and port.
apiVersion: v1
kind: Service
metadata:
  # name: A unique name for the ClusterIP service.
  name: jellyfin-clusterip-svc
  namespace: media
  labels:
    app: jellyfin
spec:
  # type: ClusterIP is the default, but explicitly stating it is clearer.
  type: ClusterIP
  # selector: Selects the Pods to send traffic to. Must match the labels on the Pods (spec.template.metadata.labels).
  selector:
    app: jellyfin
  ports:
    # HTTP Port
    - protocol: TCP
      port: 8096
      targetPort: 8096
      name: http

    #HTTPS Port
    - protocol: TCP
      port: 8920
      targetPort: 8920
      name: https