apiVersion: v1
kind: Service
metadata:
  name: jellyfin-external
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
  type: LoadBalancer #specify loadBalancer type service.  After metalLB is configured on the cluster.  
  loadBalancerIP: 10.0.100.21 #target IP for the service.
