# External LoadBalancer Service for the default (Test Server VLAN)

apiVersion: v1
kind: Service
metadata:
  name: plex-external-default
  namespace: media
spec:
  selector:
    app: plex
  ports:
    - protocol: TCP
      port: 80
      targetPort: 32400
      name: http
  type: LoadBalancer
  loadBalancerIP: 10.0.100.22 # Target IP for the LB service.