# External LoadBalancer Service for the (mgmt VLAN)

apiVersion: v1
kind: Service
metadata:
  name: plex-external-mgmt
  namespace: media
  # annotation to use vlan-mgmt IP address Pool
  annotations:
    metallb.io/address-pool: vlan-mgmt
spec:
  selector:
    app: plex
  ports:
    - protocol: TCP
      port: 80
      targetPort: 32400
      name: http
  type: LoadBalancer
  loadBalancerIP: 10.0.250.215 # Target IP for the LB service.
  externalTrafficPolicy: Local # Preserves source IP; Forces traffic to local node of pod.