apiVersion: v1
kind: Service
metadata:
  name: influxdb-external
  #namespace: default # Or your namespace
spec:
  selector:
    app: influxdb # This label should match your Jellyfin Deployment's pod labels
  ports:
    - protocol: TCP
      port: 80       # External port for the Service (what you connect to)
      targetPort: 8086 # Internal port of the container deployment
      name: http
  type: LoadBalancer 
  loadBalancerIP: 10.0.100.15 #target IP for the service.
#test to see if can direct to container deployment without specifing the port.