# --- PersistentVolumeClaim (PVC) for InfluxDB Data ---
# Requests storage, expected to be provisioned on CephFS via the specified StorageClass.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc # Name for the Persistent Volume Claim
  labels:
    app: influxdb
spec:
  accessModes:
    # ReadWriteOnce is usually appropriate for InfluxDB unless using specific clustering.
    # CephFS also supports ReadWriteMany (RWX) if needed, but check InfluxDB compatibility.
    - ReadWriteOnce
  storageClassName: rook-ceph-rbd
  resources:
    requests:
      # Set the amount of storage needed for InfluxDB data.
      storage: 10Gi # Example: 5 Gigabytes - ADJUST AS NEEDED
  # IMPORTANT: Replace with the StorageClass name for your CephFS provisioner.