# --- Deployment ---
# Pod deployment of your containerized app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-kasm-deployment
  labels:
    app: ubuntu-kasm
spec:
  replicas: 1 # Multiple instances not beneficial to this kind of deployment and would be too much of a resource strain.
  selector:
    matchLabels:
      app: ubuntu-kasm
  template:
    metadata:
      labels:
        app: ubuntu-kasm
    spec:
      containers:
      - name: ubuntu-kasm
        image: kasmweb/core-ubuntu-noble:1.16.0-rolling-daily
        ports:
        - containerPort: 6901 # Port the container will connect on.
          name: ubuntu-http
        volumeMounts:
        - name: ubuntu-kasm-data
          mountPath: /home/kasm # Mount path for data. (will need to test.) Path as described is /home/{user}
        resources:
          requests: # resource reuqests/limits. Making limits a bit higher as this is suppose to be a full desktop deployment.
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "4096Mi"
            cpu: "4000m"
        #env: 
        #- name: env_variable
        #  value: value
      volumes:
      - name: ubuntu-kasm-data # Same as name of volumeMounts.
        persistentVolumeClaim:
          claimName: ubuntu-kasm-pvc
    
            



