# --- ClusterIP Service ---
# Exposes the application Pods on a stable IP address *within* the cluster.
# Other applications inside the cluster can reach your app via this Service's name and port.
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-kasm-clusterip-svc
  labels:
    app: ubuntu-kasm
spec:
  type: ClusterIP # Default service but defining for clarity.
  selector:
    app: ubuntu-kasm
  ports:
    - name: https
      protocol: TCP
      # port and targetPort same as its just for inter-cluster communication.
      port: 6901
      targetPort: 6901