# --- PersistentVolumeClaim (PVC) ---
# This requests persistent storage from the cluster.
# This is used with app-pv-nfs.yaml and need to be deplopyed first before this yaml,
# so the PV exists for this PVC to bind to. So the storage is defined in the cluster. 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-kasm-pvc # PVC claim name.
  labels:
    app: ubuntu-kasm
spec:
  storageClassName: nfs
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 20Gi # Must be euqal to or less than the PV claim.
  selector:
    matchLabels:
      app: ubuntu-kasm # This label should match the labels of your app.