#PV needs to be deployed before the app-pvc-nfs.yaml file.
#This tells kubernetes where the storage is and removes the need for NFS to be mounted to the host. 
#PV is a static resource in the cluster well the PVC is the request of that resource.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv #unique name for PV.
  labels:
    app: pihole
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi # Space requested and maximum PVC can request.
  accessModes:
    -ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # So data persists on the PV even after deletion.
  nfs:
    server: 10.0.100.20 # Remote address of the NFS share the PV will be housed on.
    path: /mnt/storage_pool/microk8s/pihole # path to the remote storage. CHECK the final destination folder exists.