apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
  #annotations:
    # Optional: For MetalLB, if you want a specific IP from your pool
    # metallb.universe.tf/address-pool: my-pihole-pool 
    # metallb.universe.tf/allow-shared-ip: pihole-svc # If sharing IP with another service
spec:
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  # Optional: To request a specific IP from your MetalLB pool
  # loadBalancerIP: "192.168.1.200"