apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-external
  #namespace: pihole
spec:
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
  # Optional: To request a specific IP from your MetalLB pool
  loadBalancerIP: "10.0.100.2"
  externalTrafficPolicy: Local # Force the Service to no do any cross node hopping so the traffic goes to the pods hosting node. Should preserve the original hosts IP.