# --- NodePort Service ---
# Exposes the application Pods on a static port on each Node's external IP address.
# Accessible from outside the cluster via <NodeIP>:<NodePort>. Use with caution or behind a load balancer in production.
apiVersion: v1
kind: Service
metadata:
  # name: A unique name for the NodePort service.
  name: grafana-nodeport-svc
  labels:
    app: grafana
spec:
  # type: NodePort makes the service accessible on each Node's IP at a specific port.
  type: NodePort
  # selector: Selects the Pods to send traffic to. Must match the labels on the Pods.
  selector:
    app: grafana
  ports:
    # - protocol: Usually TCP.
  - protocol: TCP
    # port: The port this Service listens on *within the cluster* (a ClusterIP is still assigned).
    port: 3000 # e.g., 80
    # targetPort: The port on the Pods (containerPort) to forward traffic to.
    targetPort: 3000 # e.g., 8080 (must match containerPort in Deployment) or 'http' if named
    # nodePort: (Optional) The static port exposed on each Node's IP.
    # If specified, must be in the configured NodePort range (default: 30000-32767).
    # If omitted, Kubernetes assigns a random available port from the range.
    nodePort: 30300 # e.g., 30080