apiVersion: v1
kind: Service
metadata:
  name: heimdall-external
  namespace: default
spec:
  selector:
    app: heimdall
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer #specify loadBalancer type service.  After metalLB is configured on the cluster.  
  loadBalancerIP: 10.0.100.30 #target IP for the service.
