# --- PersistentVolumeClaim (PVC) ---
# This requests persistent storage from the cluster.
# This is used with app-pv-nfs.yaml and need to be deplopyed first before this yaml,
# so the PV exists for this PVC to bind to. So the storage is defined in the cluster. 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-pvc  #pvc claim name
  labels:
    app: heimdall
spec:
  accessModes:
    - ReadWriteMany  #needs to be Many since shared location
  resources:
    requests:
      storage: 5Gi  #Must be equal or less than PV claim
  selector:
    matchLabels:
      app: heimdall # This label should match the labels of your PV
