apiVersion: v1
kind: Service
metadata:
  name: heimdall-external
spec:
  selector:
    app: heimdall
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 10.0.100.30


