# --- Deployment ---
# Manages the Pods running your application container.
apiVersion: apps/v1
kind: Deployment
metadata:
  # name: A unique name for your Deployment.
  name: <your-app-name>-deployment
  labels:
    app: <your-app-name>
spec:
  replicas: <replica-count> # e.g., 2
  selector:
    # Must match the labels on the Pod template below.
    matchLabels:
      app: <your-app-name>
  template:
    metadata:
      # Labels applied to the Pods created by this Deployment. Must match spec.selector.matchLabels.
      labels:
        app: <your-app-name>
    spec:
      containers:
      - name: <your-app-container-name>
        image: <your-docker-image>:<tag> # e.g., your-repo/your-app:latest
        ports:
        - containerPort: <container-port> # The port your application listens on INSIDE the container (e.g., 8080)
          name: http # Optional name for the port
        # volumeMounts: Mounts the volume requested by the PVC into the container.
        volumeMounts:
        - name: <your-app-storage-volume-name> # Must match the volume name defined below in spec.volumes / lowercase only.
          # mountPath: The directory path inside the container where the storage will be accessible.
          mountPath: <path-inside-container-for-storage> # e.g., /app/data or /var/www/html
        # --- Optional but Recommended ---
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "250m"
        # env:
        # - name: MY_ENV_VAR
        #   value: "my_value"
        # livenessProbe: ... (configure as needed)
        # readinessProbe: ... (configure as needed)

      # volumes: Defines the volumes available to the Pod.
      volumes:
      # - name: Must match the name used in volumeMounts above.
      - name: <your-app-storage-volume-name> # e.g., app-data. Must be all lowercase.
        # persistentVolumeClaim: Links this volume definition to the PVC created earlier.
        persistentVolumeClaim:
          # claimName: Must match the metadata.name of the PVC defined above.
          claimName: <your-app-name>-pvc