# --- PersistentVolumeClaim (PVC) ---
# This requests persistent storage from the cluster.
# This is used with app-pv-nfs.yaml and need to be deplopyed first before this yaml,
# so the PV exists for this PVC to bind to. So the storage is defined in the cluster. 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-homarr-pvc  #pvc claim name
  namespace: homarr
  labels:
    app: postgreHomarr
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  #Must be equal or less than PV claim
  selector:
    matchLabels:
      app: postgreHomarr # This label should match the labels of your PV
