apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc  #pvc claim name
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteMany  #needs to be Many since shared location
  resources:
    requests:
      storage: 5Gi  #match the PV claim
  selector:
    matchLabels:
      app: nginx # This label should match the labels of your PV