# --- PersistentVolumeClaim (PVC) ---
# This requests persistent storage from the cluster.
# The actual storage (PersistentVolume) is usually provisioned dynamically based on the StorageClass.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # name: A unique name for your PVC. This will be referenced by the Deployment.
  name: nginx-pvc
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # Must be >= PVC request
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain # Or Recycle/Delete
  # Use hostPath pointing to your identical NFS mount point
  hostPath:
    path: "/mnt/microk8s/nginx-data" # Use the host path (maybe a subdirectory)
    type: DirectoryOrCreate # Ensure the directory exists